# Generated by Django 3.2.3 on 2021-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibasics', '0002_rename_type_loan_typeof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='starting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
