# Generated by Django 3.2.3 on 2021-05-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibasics', '0003_auto_20210528_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='starting_date',
            field=models.DateField(blank=True),
        ),
    ]
